### ISSUE TITLE
Failed to generate changelog

### ISSUE THREAD

**Issue by andrevenancio** [dragonraid/changelog-generator#2]
Hi, I'm having this issue:

```
Error: Failed to generate changelog due to: Error: Either GITHUB_TOKEN environment variable or "github_token" input must be set.
```

Can you clarify on how to create the github_token you mention on the README.md?

**Comment by dragonraid** [comment]
Hi @andrevenancio,

thank you for your query! In general I have written this action, because at the time there were no "simple enough" tools to help me with such task. Since then, github presented their [release-notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes). Other tool i recently started to use is [release-please](https://github.com/google-github-actions/release-please-action) action from googleapis.

That being said, I do not maintain this action anymore and I'd recommend to you to adopt some tool that has bigger community and is well supported (such as tools, I mentioned above).

Nevertheless if you insist on using this action.  Usage should be clear from [README](https://github.com/dragonraid/changelog-emitter#example). [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) is provided by github. You just need to provide it to action like this:

```yaml
...
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by dragonraid** [comment]
Closing as resolved.
